package ch.so.agi.hop.geoprocessing.core;

public enum ParameterId {
  PRIMARY_GEOMETRY,
  SECONDARY_GEOMETRY,
  DISTANCE,
  DISTANCE_MODE,
  DISTANCE_FIELD,
  BUFFER_SEGMENTS,
  BUFFER_CAP_STYLE,
  BUFFER_JOIN_STYLE,
  BUFFER_SINGLE_SIDED,
  OUTPUT_FIELD,
  OUTPUT_MODE,
  RESULT_MODE,
  BOOLEAN_FIELD,
  FIELD_PREFIX,
  GROUP_FIELDS
}
